Revert "Update geoip2 to 4.2.0"
This reverts commit c994b6eed0f175af7eb319ebf334eb7da0685159.

It prevents lila from starting:

```
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.14.3 requires Jackson Databind version >= 2.14.0 and < 2.15.0 - Found jackson-databind version 2.16.0
```