downgrade to chessground 7.6.5
Before the chessground es6 commit, which breaks the lila build:

[00:39:40] Using gulpfile ~/build/ornicar/lila/ui/editor/gulpfile.js
[00:39:40] Starting 'prod'...
[00:39:41] 'prod' errored after 1.23 s
[00:39:41] Error:
/home/travis/build/ornicar/lila/node_modules/chessground/chessground.js:1
import { start } from './api';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
    at formatError (/home/travis/build/ornicar/lila/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/home/travis/build/ornicar/lila/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (events.js:203:15)
    at Gulp.EventEmitter.emit (domain.js:448:20)
    at Object.error (/home/travis/build/ornicar/lila/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/travis/build/ornicar/lila/node_modules/now-and-later/lib/map.js:50:14)
    at f (/home/travis/build/ornicar/lila/node_modules/once/once.js:25:25)
    at f (/home/travis/build/ornicar/lila/node_modules/once/once.js:25:25)
    at tryCatch (/home/travis/build/ornicar/lila/node_modules/async-done/index.js:24:15)
    at done (/home/travis/build/ornicar/lila/node_modules/async-done/index.js:40:12)
parallel: This job failed:
build editor