store async cache total load time in millis
nanos won't do:
k.m.instrument.HdrHistogram -
Failed to store value 5318471045655 in HdrHistogram, please review your
range configuration.
java.lang.ArrayIndexOutOfBoundsException: value outside of histogram
covered range. Caused by: java.lang.IndexOutOfBoundsException: index
4634