build custom reactivemongo 0.12.1 with iteratees 2.4
** BREAKS LILA INCREMENTAL BUILD ** so follow these steps:

```
./bin/build-deps
./bin/dev (or sbt if you don't use bin/dev)
clean
compile
```

This is required to upgrade reactivemongo. The default version
compiled with iteratees 2.6 breaks at runtime with:

java.lang.NoSuchMethodError: play.api.libs.iteratee.Execution$Implicits$.trampoline()