fix oauth authorization page for `web:mod` scope
when an app requests `web:mod` scope, lila adds `ok-cancel-confirm` class which displays a modal before submitting. Clicking "yes" in the modal tries to click the form element that is no longer present in the DOM.

```
TypeError: Cannot read properties of null (reading 'remove')
```