Revert "code golf with cats.mtl.Handle"
This reverts commit 47f01e9c8e7eda7b0a707c8b4cc6a8e0a82184d7.

```
play.api.UnexpectedException: Unexpected exception[NullPointerException: Cannot invoke "String.isEmpty()" because "string" is null]
        at play.api.UnexpectedException$.apply(Exceptions.scala:10)
Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "string" is null
        at akka.util.CompactByteString$.apply(ByteString.scala:1033)
        at akka.util.ByteString$.apply(ByteString.scala:57)
        at play.api.mvc.Codec$.javaSupported$$anonfun$1(Results.scala:442)
        at play.api.http.DefaultWriteables.wString$$anonfun$1(Writeable.scala:201)
        at play.api.http.Writeable.toEntity(Writeable.scala:22)
        at play.api.mvc.Results$Status.apply(Results.scala:531)
        at controllers.Fishnet$$anon$1.applyOrElse(Fishnet.scala:47)
        at controllers.Fishnet$$anon$1.applyOrElse(Fishnet.scala:44)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        ... 11 common frames omitted
2025-10-06 06:24:22,941 ERROR play.core.server.netty.PlayRequestHandler Cannot invoke the action
java.lang.NullPointerException: null
2025-10-06 06:24:22,941 ERROR lila.app.http.ErrorHandler

! @8b2cappae - Internal server error, for (POST) [/fishnet/analysis/tciRL5If?slow=false&stop=true] ->
```