scalac bug
java.lang.AssertionError: assertion failed: TS[10250527, 10250526, 10250525] attempted to take ownership of S which is already owned by committable TS[10261739, 10250527, 10250526, 10250525] while typechecking /home/thib/lila/modules/tutor/src/main/TutorBuilder.scala
[info] exception occurred while typechecking /home/thib/lila/modules/tutor/src/main/TutorBuilder.scala