fix hopscotch moved to ui/pagelets
```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error: ENOENT: no such file or directory, watch '/home/thib/lila/ui/site/node_modules/hopscotch/dist'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at copies (/home/thib/lila/ui/.build/dist/copies.js:65:32)
    at async build (/home/thib/lila/ui/.build/dist/build.js:65:5) {
  errno: -2,
  syscall: 'watch',
  code: 'ENOENT',
  path: '/home/thib/lila/ui/site/node_modules/hopscotch/dist',
  filename: '/home/thib/lila/ui/site/node_modules/hopscotch/dist'
}
```